### ISSUE TITLE
Improve localization integration with setup.py

### ISSUE THREAD

**Issue by sanyavertolet** [teamvolik/teamvolik#43] opened 2022-04-18 23:11 UTC
We will need to add some commands in order to generate translations with `setup.py`. [Here](https://github.com/pdfkpb/OctoPrintCluster/blob/master/src/octoprint_setuptools/__init__.py) is something that might work.

**Comment by dgreflex** [comment] 2022-06-15 23:23
Duplicate of #51

**Closed as completed by dgreflex** 2022-06-15 23:23 UTC
Labels: duplicate
